groups:
  - name: self-healing-rules
    rules:
      - alert: NginxDown
        expr: probe_success{job="http_probe"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "NGINX is down"
          description: "NGINX has been unreachable for 30s."

      - alert: HighCPUUsage
        expr: (1 - avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[2m]))) * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU > 90% for 2m"
