global:
  scrape_interval: 10s
  scrape_timeout: 8s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]   # Alertmanager service inside docker-compose

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["node_exporter:9100"]   # service name

  - job_name: http_probe
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://nginx:80/              # nginx service name + port inside docker
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115   # service name
